common: &common
  adapter: postgresql
  username: stockmktdb
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: stockmktdb_dev

test:
  <<: *common
  database: stockmktdb_test

production:
  <<: *common
  database: stockmktdb_prod
  